### Create
POST http://localhost:8080/articletype/create
Content-Type: application/json
Profilerole: ADMIN
{
  "nameUz": "Article uz",
  "nameRu": "ru",
  "nameEn": "en",
  "orderNumber": 4
}

### updateById

PUT http://localhost:8080/articletype/update/3
Content-Type: application/json
Profilerole: ADMIN
{
  "nameUz": "Dolzarb",
  "nameEn": "Actual",
  "nameRu": "Актуальные ",
  "orderNumber": 3
}

### getAll
GET http://localhost:8080/articletype/admin/all?page=1&size10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1NDE0NzgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2Mjc4NzgsImlzcyI6Ikt1blV6VGVzdCJ9.dWo3jg9kQz-LT2Ns3LMu1E7T5D7F9ze_cIqt8MH15n9b4WPEgU5FcZlZCCHFmAjmrpUl37jaOLUsFT5S0qOhJA

### getByLang
GET http://localhost:8080/articletype/getByLang?id=1&lang=uz