### Create
POST http://localhost:8080/articletype/create
Content-Type: application/json
Profilerole: ADMIN
{
  "nameUz": "Article uz",
  "nameRu": "ru",
  "nameEn": "en",
  "orderNumber": 4
}

### updateById

PUT http://localhost:8080/articletype/update/3
Content-Type: application/json
Profilerole: ADMIN
{
  "nameUz": "Dolzarb",
  "nameEn": "Actual",
  "nameRu": "Актуальные ",
  "orderNumber": 3
}

### getAll
GET http://localhost:8080/articletype/all?page=1&size10

### getByLang
GET http://localhost:8080/articletype/getByLang?id=1&lang=uz