### Update
PUT http://localhost:8080/article/adm/update/b1907197-5dd8-4501-b2cb-721a16cb899e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcxMzg0MzMsImlkIjo0Miwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA3MjI0ODMzLCJpc3MiOiJLdW5VelRlc3QifQ.UpAjKrwL6ovkuQNyhGrkw_OfRloOct7wgzy2dt-yxP7AfYjqqgl-iPablNHlJ_xEgTIxyy87KeYToJbXoKodJw

{
  "title": "Update title",
  "description": "Update description",
  "content": "update content"

}

### Create
POST http://localhost:8080/article/adm/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczMTExNzgsImlkIjo0Miwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA3Mzk3NTc4LCJpc3MiOiJLdW5VelRlc3QifQ.O1RbKKzNuwH8uiSGUzoeqllYoH0HsLnLJMh6jenvPIhjYGHj11XLNaQ7vbQURG-IYunbSKSAUUE9wgRRxZIH6w
Content-Type: application/json

{
  "title": "Dolzarb",
  "description": "Dolzarb habarlar hammasi shu yerda",
  "content": "html codes",
  "regionId": 2,
  "categoryId": 1,
  "articleType": [1],
  "photoId": "b2538f31-1502-4b18-b955-e7374dc65054"
}

