### Login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "xabibulloyevixtiyorxon@gmail.com",
  "password": "12345"
}


### Registration
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "phone": "998950490629",
  "name": "Alish",
  "surname": "Aliyev",
  "email": "ewfjo572odsdcaweqw0jf@gmail3.com",
  "password": "12345"
}
