### Login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "xabibulloyevixtiyorxon@gmail.com",
  "password": "12345"
}


###
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Ixtiyorxon",
  "surname": "Xabibulloyev",
  "email": "xabibulloyevixtiyorxon@gmail.com",
  "password": "123433"
}
