### create
POST http://localhost:8080/category/create
Content-Type: application/json

{
  "nameUz": "O'zbekiston",
  "nameRu": "Узбек",
  "nameEn": "Uzbekistan",
  "orderNumber": 1
}

### hammasi
GET localhost:8080/category/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1NDE0NzgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2Mjc4NzgsImlzcyI6Ikt1blV6VGVzdCJ9.dWo3jg9kQz-LT2Ns3LMu1E7T5D7F9ze_cIqt8MH15n9b4WPEgU5FcZlZCCHFmAjmrpUl37jaOLUsFT5S0qOhJA