### create
POST localhost:8080/region/create
Content-Type: application/json

{
  "nameUz": "Sirdaryo uz",
  "nameRu": "Sirdaryo ru",
  "nameEn": "Sirdaryo en",
  "orderNumber": 2
}

### deleteById
DELETE http://localhost:8080/region/3

### all
GET http://localhost:8080/region/all

### getByLan
GET http://localhost:8080/region/getByLang?lang=uz