### create
POST localhost:8080/region/create
Content-Type: application/json
profileRole: ADMIN
{
  "nameUz": "Sam uz",
  "nameRu": "sam ru",
  "nameEn": "sam en",
  "orderNumber": 4
}

### deleteById
DELETE http://localhost:8080/region/3

### all
GET http://localhost:8080/region/all

### getByLan
GET http://localhost:8080/region/getByLang?lang=uz